apiVersion: v1
kind: Service          # This tells Kube: "I am a Service"
metadata:
  name: purple-service # The name of this "Phonebook"
spec:
  type: NodePort       # This makes it accessible from your browser
  selector:
    app: web           # This tells it: "Find any pods with the label 'web'"
  ports:
    - port: 80         # Internal port
      targetPort: 80   # The port inside your container
      nodePort: 30001  # THE PORT YOU TYPE IN YOUR BROWSER
